### ISSUE TITLE
No LUA 5.1 support?

### ISSUE THREAD

**Issue by CriztianiX** [isage/lua-resty-moongoo#1]
Hey, check this out!

Using luajit, this works
```bash
[mundodescuento@localhost ~]$ luajit counting.lua
1000
```

But using lua 5.1 with:

```bash
luabitop
   1.0.2-3 (installed) - /usr/lib/luarocks/rocks
luacrypto
   0.3.2-2 (installed) - /usr/lib/luarocks/rocks
luasocket
   3.0rc1-2 (installed) - /usr/lib/luarocks/rocks
``` 
I get
```bash
[mundodescuento@localhost ~]$ lua counting.lua
lua: /usr/share/lua/5.1/resty/moongoo/connection.lua:61: closed
stack traceback:
        [C]: in function 'assert'
        /usr/share/lua/5.1/resty/moongoo/connection.lua:61: in function </usr/share/lua/5.1/resty/moongoo/connection.lua:60>
        (tail call): ?
        /usr/share/lua/5.1/resty/moongoo/database.lua:42: in function '_cmd'
        /usr/share/lua/5.1/resty/moongoo.lua:68: in function 'connect'
        /usr/share/lua/5.1/resty/moongoo/database.lua:22: in function 'cmd'
        /usr/share/lua/5.1/resty/moongoo/cursor.lua:202: in function 'count'
        counting.lua:13: in main chunk
        [C]: ?
```

**Comment by CriztianiX** [comment]
This one http://luaforge.net/projects/bitlib/ ?

**Comment by isage** [comment]
yep

**Comment by CriztianiX** [comment]
I cannot test!
I 've some dependencies using bitOp, so, i cannot remove it

Anyway the page says the following

> bitlib is a tiny library for bitwise operations. It is now deprecated in favour of bitop: http://bitop.luajit.org/

**Comment by isage** [comment]
well, yep. they should be compatible. sorry, i can take a look at it only
after holidays. meanwhile, is there something standing out in mongodb logs?

**Comment by CriztianiX** [comment]
Wow... in mongodb logs i get:

> 2016-12-28T22:53:50.437+0000 [conn118] AssertionException handling request, closing client connection: 17132 SSL handshake received but server is started without SSL support

**Comment by isage** [comment]
This shouldn't be related, as moongoo doesn't have support for ssl yet.
But, it seems like mongodb throws this error in completely unrelated cases.
What version of mongodb are you using?

**Comment by CriztianiX** [comment]
I'm using 
mongodb-2.6.12-3.el7.x86_64
CentOS Linux release 7.2.1511 (Core)

**Comment by CriztianiX** [comment]
The same error runing on Ubuntu 16.04
 mongodb-server                              1:2.6.10-0ubuntu1

**Comment by isage** [comment]
Okay, that's a bug in lua-cbson
Should be fixed with https://github.com/isage/lua-cbson/commit/de748dab19e5e56aa3faf7c214c70a96d2b62ea5

**Comment by CriztianiX** [comment]
Good notice!! Works like a Charm!
