### ISSUE TITLE
How to extract _id

### ISSUE THREAD

**Issue by mliker** [isage/lua-resty-moongoo#10]
I looked at you lua-cbson project, but still can't figure it out.

```lua
local doc, err = users:find_one({ email = "user@domain.com" })
for k,v in pairs(doc) do
  ngx.say(k,v)
end
```
results in:
`bad argument #2 to 'say' (string, number, boolean, nil, ngx.null, or array table expected, but got userdata)`

**Comment by isage** [comment]
Sadly, openresty's ngx.say doesn't automatically call __tostring metamethod on userdata, as opposed to lua's print.
So you'll need to explicitly call tostring yourself, e.g.:
```
local doc, err = users:find_one({ email = "user@domain.com" })
for k,v in pairs(doc) do
  ngx.say(tostring(k), tostring(v))
end
```

**Comment by mliker** [comment]
Excellent! Thank you for your answer.
