### ISSUE TITLE
Cant connecto to servers in mlab

### ISSUE THREAD

**Issue by CriztianiX** [isage/lua-resty-moongoo#11]
Trying to connect mongod version: 3.4.7 in mlab cloud.
In insert i get:
collection.lua:100: bad argument #1 to 'gsub' (string expected, got nil)

self._db._moongoo:connect() returns:
nil , Can't connect to any of servers

I'm using master branch. So: https://github.com/isage/lua-resty-moongoo/issues/8 seems not work

**Comment by isage** [comment]
#8 is unrelated (it works)
There's either some error in your connection string, or something else. Can you provide more details?
What mg:connect()  returns (mg being an instance of moongoo)?

**Comment by CriztianiX** [comment]
You can test using this db 

mongodb://<dbuser>:<dbpassword>@ds119014.mlab.com:19014/my_test_db

dbuser = my_test_user
pass = qwe123
collection = my_test_collection

**Comment by isage** [comment]
well, 
```lua
local mg = require("resty.moongoo")

local mongo, err = mg.new("mongodb://my_test_user:qwe123@ds119014.mlab.com:19014/")

local r, err = mongo:connect()

print(err)
```
gives me `Authentication failed.`

**Comment by isage** [comment]
However, it's indeed working with command-line client. I'll need some time to debug it.

**Comment by CriztianiX** [comment]
In NodeJS working too...

```bash
$ nodejs index.js 
Connected successfully to server
```

```javascript
var MongoClient = require('mongodb').MongoClient
  , assert = require('assert');

// Connection URL
var url = 'mongodb://my_test_user:qwe123@ds119014.mlab.com:19014/my_test_db';

// Use connect method to connect to the server
MongoClient.connect(url, function(err, db) {
  assert.equal(null, err);
  console.log("Connected successfully to server");

  db.close();
});
```

**Comment by isage** [comment]
So, i've inserted some data in this collection through cli (`db.my_test_collection.insert({test: "test"})`)
And this code
```lua
local mg = require("resty.moongoo")
local printr = require("resty.moongoo.utils").print_r

local mongo, err = mg.new("mongodb://my_test_user:qwe123@ds119014.mlab.com:19014/my_test_db")

local col,err = mongo:db("my_test_db"):collection("my_test_collection"):find_one({})
printr(col)

```

works as expected:
```
$ luajit ./test.lua 
[_id] = 59a86afbee37059c113159f9
[test] = test

```

**Comment by CriztianiX** [comment]
Not for me...

```lua
local mg = require("resty.moongoo")
local printr = require("resty.moongoo.utils").print_r
local mongo, err = mg.new("mongodb://my_test_user:qwe123@ds119014.mlab.com:19014/my_test_db")
local col,err = mongo:db("my_test_db"):collection("my_test_collection"):find_one({})
printr(col)
printr(err)
nil
Can't connect to any of servers,
```

and insert:

```lua
local mg = require("resty.moongoo")
local printr = require("resty.moongoo.utils").print_r
local mongo, err = mg.new("mongodb://my_test_user:qwe123@ds119014.mlab.com:19014/my_test_db")
local col,err = mongo:db("my_test_db"):collection("my_test_collection"):insert({key = "val"})

/usr/local/openresty/lualib/resty/moongoo/collection.lua:100: bad argument #1 to 'gsub' (string expected, got nil)
```

**Comment by isage** [comment]
Well, that's strange. And this is on the same machine, where cli's working?

**Comment by CriztianiX** [comment]
Ooooo.... i'm so st#pid!

resolve(): Can't connect to any of servers.

In my nginx.conf i've added

resolver 8.8.8.8

Now, working...
