### ISSUE TITLE
Count returns userdata?

### ISSUE THREAD

**Issue by CriztianiX** [isage/lua-resty-moongoo#13]
Why count() returns userdata instead int?

```lua
local x = mongo.get_collection("my_test_collection"):find({})
local a = x:count()
type(a)
```
```
handler(): "userdata"
```

**Comment by isage** [comment]
That's because lua-cbson (and so lua-moongoo) decodes all numbers as
cbson.int/cbson.uint. You can, however, compare them to normal lua numbers
(to some extent, because lua number limit is smaller than C/mongo one,
because internally all numbers in lua 5.1 are floats)
