### ISSUE TITLE
should I close file after slurping from GridFS?

### ISSUE THREAD

**Issue by jetz** [isage/lua-resty-moongoo#15]
Hi @isage:

The readme doc has told when create file in GridFS, close should be called, that's clear.

But usually we also close a file after opening for reading. so, should I close file after slurping from GridFS, I try it, but raise error (file.lua 150 line, nil value).

**Comment by isage** [comment]
No, you shouldn't. close is just for writing: as it's said in docs, it just writes metadata and last chunk.
I guess i should've called it finalize, to avoid confusion.

**Comment by jetz** [comment]
@isage Got it! thanks for your quick reply.
