### ISSUE TITLE
Force writing array instead of object?

### ISSUE THREAD

**Issue by travisbell** [isage/lua-resty-moongoo#17]
Hey man,

I know you mentioned in the docs that for now you decided to store empty tables as objects instead of arrays. I wonder, would it be possible to have a cbson type to force the storage as a cbson array instead? Kind of like what you did with storing nil?

**Comment by isage** [comment]
Sure. I've added cbson.array() to lua-cbson.

**Comment by travisbell** [comment]
Awesome man, thanks! 👍

**Comment by travisbell** [comment]
Hey @isage I've just been trying to use this and can't seem to get it to work. Trying to store a cbson.array() seems to just silently fail and I can't figure out where the issue is.

Do you have a working example that I can see?

**Comment by isage** [comment]
It looks like mongo libbson doesn't like BSON_APPEND_ARRAY with empty arrays and segfaults.
Fixed in latest commit to lua-cbson

**Comment by travisbell** [comment]
Yup, looks good. It's not segfaulting anymore. Thanks.
