### ISSUE TITLE
Does this module support TLS connections?

### ISSUE THREAD

**Issue by mmaberry-yottaa** [isage/lua-resty-moongoo#18]
We would like to use this module to connect to MongoDB Atlas (DAAS from mongodb)  - https://www.mongodb.com/cloud/atlas. Clients must have support for TLS/SSL to connect to an Atlas cluster.

We are using a connection string like: 

`mongodb://USERNAME:PASSWORD@some-shard-00-00-2bhzf.mongodb.net:27017,someother-shard-00-01-2bhzf.mongodb.net:27017,third-shard-00-02-2bhzf.mongodb.net:27017/DATABASE?&ssl=true`

Would be interested to know if anyone has experience using this module with Atlas or can help us understand how we could make the connection.

**Comment by isage** [comment]
Yep, it supports ssl/tls. Your connection string should work.
