### ISSUE TITLE
Openresty show "unknown process 86094 exited with code 0"

### ISSUE THREAD

**Issue by foxericlee** [isage/lua-resty-moongoo#23]
Hi guy,
Thank you for you lua-resty-moongoo. I think it's a cool lua driver for mongodb. But there is a problem. When I exec ’local moongoo = require("resty.moongoo")‘。Then openresty log show as blow.

2018/08/15 12:28:15 [notice] 4737#4737: signal 17 (SIGCHLD) received from 86015
2018/08/15 12:28:15 [notice] 4737#4737: unknown process 86015 exited with code 0

Is there anything wrong? Waiting for your response, thank you.

**Comment by foxericlee** [comment]
The example can run. Just show the notice, and seem no influence.

**Comment by nomusics** [comment]
`nginx.conf` server

```
lua_code_cache off;
```
