### ISSUE TITLE
Number returned as userdata.

### ISSUE THREAD

**Issue by StartAt24** [isage/lua-resty-moongoo#28]
If the data type is number, "find" will returns a userdata。 So i have to convert it to number like
`tonumber(tostring(xxxx))`。
It's not convenient. 
Is there an easy way to do this? 
Or can i get the right type of the data  as it stored in mongodb?

**Comment by isage** [comment]
See https://github.com/isage/lua-resty-moongoo#note
There's no such datatype as "number" in mongo. It's either int32, int64 or double.
Lua number datatype is always double, that's just how it is (except in Lua 5.3, but this library targets lua 5.1/luajit). So there's no way to map true int32/int64 to lua number, thus userdata, and using `tonumber(tostring(xxxx)) ` is discouraged.

Use cbson types for comparison, etc. use tostring for output.

**Comment by StartAt24** [comment]
Thanks for your reply. 
Replace `tonumber(tostring()) with userdata:number()`

**Comment by isage** [comment]
It'll still fail on numbers > 2^53
