### ISSUE TITLE
bson_append_binary(): precondition failed: binary

### ISSUE THREAD

**Issue by dev0pz** [isage/lua-resty-moongoo#34]
Hi. I was having issues when trying to connect to MongoDB > 3.2 using user:password in its mongodb uri and only in such case, no problems at all with non authenabled mongodbs.

I was using debian stretch openresty openresty/1.15.8.1 
with current lua-resty-moongoo master
with your compiled Lua-cbson trying with both: compiling libbson 1.7.0 and then with the recent libbson 1.9.5

everything works perfect with non authenticaticated connections but whenever i try to connect using mongo credentials like mongodb://user:password@server it throws:

`src/bson/bson.c:812 bson_append_binary(): precondition failed: binary
2019/08/30 16:37:04 [alert] 1#1: worker process 6 exited on signal 6
`
when trying to query some collection.

thanks a lot, it's an amazing lib

**Comment by isage** [comment]
Can you try with patch from this pull request https://github.com/isage/lua-resty-moongoo/pull/32 ?

**Comment by dev0pz** [comment]
confirmed. it works fine. thanks a lot, will tip your hat!
