### ISSUE TITLE
nginx: [error] init_by_lua_file error: lualib/resty/mongol/init.lua:130: no request found

### ISSUE THREAD

**Issue by jclivi** [isage/lua-resty-moongoo#38]
Hi !
Excuse me, have you encountered such a problem?

nginx: [error] init_by_lua_file error: lualib/resty/mongol/init.lua:130: no request found
stack traceback:
[C]: in function 'socket'
lualib/resty/mongol/init.lua:130: in function 'new'

**Comment by isage** [comment]
No. And how's that relevant to resty-moongoo?

**Comment by jclivi** [comment]
Thank you !

Nginx prohibits socket in init_by_lua*
