### ISSUE TITLE
server_version causing error in newer Mongo versions.

### ISSUE THREAD

**Issue by develephant** [isage/lua-resty-moongoo#8]
Hi,

Both version 2.6.10 and 3.4 throw:

`bad argument #1 to 'gsub' (string expected, got nil)`

Works fine when commenting out the offending lines. Seems related to #6 

I tried poking around but was unable to create a fix.

-dev

**Comment by isage** [comment]
Does it help to call mg:connect() before issuing insert?

**Comment by develephant** [comment]
Hi,

Thank you for the reply, and also the module.

I'll give it a try the next time I have the project up and report back.

-dev

**Comment by develephant** [comment]
Hi,

I modified the collection.lua with:

```lua
...

self._db._moongoo:connect()

local server_version = tonumber(string.sub(string.gsub(self._db._moongoo.version, "(%D)", ""), 1, 3))

...
```

And that seems to work perfectly. 👍
