### ISSUE TITLE
aggregate cursor loses _db reference

### ISSUE THREAD

**Issue by develephant** [isage/lua-resty-moongoo#9]
Hi,

While testing the aggregate method with a cursor return, an error is thrown on any of the cursor methods. For example: `curs:all()` or `curs:count()`

```
attempt to index field '_db' (a nil value)
```

The other two varieties of the aggregate method work fine (using `explain` or `$out`).

-dev

**Comment by isage** [comment]
Can you at least provide a filename and line number of an error?

**Comment by develephant** [comment]
My apologies for not responding sooner. For whatever reason, I didn't get an email for your response. 

Thank you for the fix. It is very much appreciated. 👍 

-dev
